import HeroComponentEight from "./ArrayComponentsForDesigns/HeroSectionArrayComponentFolder/HeroComponentEight";
import HeroComponentFive from "./ArrayComponentsForDesigns/HeroSectionArrayComponentFolder/HeroComponentFive";
import HeroComponentFour from "./ArrayComponentsForDesigns/HeroSectionArrayComponentFolder/HeroComponentFour";
import HeroComponentOne from "./ArrayComponentsForDesigns/HeroSectionArrayComponentFolder/HeroComponentOne";
import HeroComponentSeven from "./ArrayComponentsForDesigns/HeroSectionArrayComponentFolder/HeroComponentSeven";
import HeroComponentSix from "./ArrayComponentsForDesigns/HeroSectionArrayComponentFolder/HeroComponentSix";
import HeroComponentThree from "./ArrayComponentsForDesigns/HeroSectionArrayComponentFolder/HeroComponentThree";
import HeroComponentTwo from "./ArrayComponentsForDesigns/HeroSectionArrayComponentFolder/HeroComponentTwo";

export const heroComponents = ({
  text,
  buttonIndex,
  isMobile,
  handleDivClick,
  handleTextClick,
  getStyle,
  getElementStyle,
  index,
  isEdited,
  uniqueId,
  elementContent,
  handleImageClick,
  handleDivButtonClick,
  handleCardClick,
}) => {

  return [
    <HeroComponentOne
      text={text}
      buttonIndex={buttonIndex}
      isMobile={isMobile}
      handleDivClick={handleDivClick}
      handleTextClick={handleTextClick}
      getStyle={getStyle}
      getElementStyle={getElementStyle}
      index={index}
      isEdited={isEdited}
      uniqueId={uniqueId}
      elementContent={elementContent}
      handleImageClick={handleImageClick}
      handleDivButtonClick={handleDivButtonClick}
      handleCardClick={handleCardClick}
    />,
    <HeroComponentTwo
      text={text}
      buttonIndex={buttonIndex}
      isMobile={isMobile}
      handleDivClick={handleDivClick}
      handleTextClick={handleTextClick}
      getStyle={getStyle}
      getElementStyle={getElementStyle}
      index={index}
      isEdited={isEdited}
      uniqueId={uniqueId}
      elementContent={elementContent}
      handleImageClick={handleImageClick}
      handleDivButtonClick={handleDivButtonClick}
      handleCardClick={handleCardClick}
    />,
    <HeroComponentThree
      text={text}
      buttonIndex={buttonIndex}
      isMobile={isMobile}
      handleDivClick={handleDivClick}
      handleTextClick={handleTextClick}
      getStyle={getStyle}
      getElementStyle={getElementStyle}
      index={index}
      isEdited={isEdited}
      uniqueId={uniqueId}
      elementContent={elementContent}
      handleImageClick={handleImageClick}
      handleDivButtonClick={handleDivButtonClick}
      handleCardClick={handleCardClick}
    />,
    <HeroComponentFour
      text={text}
      buttonIndex={buttonIndex}
      isMobile={isMobile}
      handleDivClick={handleDivClick}
      handleTextClick={handleTextClick}
      getStyle={getStyle}
      getElementStyle={getElementStyle}
      index={index}
      isEdited={isEdited}
      uniqueId={uniqueId}
      elementContent={elementContent}
      handleImageClick={handleImageClick}
      handleDivButtonClick={handleDivButtonClick}
      handleCardClick={handleCardClick}
    />,
    <HeroComponentFive
      text={text}
      buttonIndex={buttonIndex}
      isMobile={isMobile}
      handleDivClick={handleDivClick}
      handleTextClick={handleTextClick}
      getStyle={getStyle}
      getElementStyle={getElementStyle}
      index={index}
      isEdited={isEdited}
      uniqueId={uniqueId}
      elementContent={elementContent}
      handleImageClick={handleImageClick}
      handleDivButtonClick={handleDivButtonClick}
      handleCardClick={handleCardClick}
    />,
    <HeroComponentSix
      text={text}
      buttonIndex={buttonIndex}
      isMobile={isMobile}
      handleDivClick={handleDivClick}
      handleTextClick={handleTextClick}
      getStyle={getStyle}
      getElementStyle={getElementStyle}
      index={index}
      isEdited={isEdited}
      uniqueId={uniqueId}
      elementContent={elementContent}
      handleImageClick={handleImageClick}
      handleDivButtonClick={handleDivButtonClick}
      handleCardClick={handleCardClick}
    />,
    <HeroComponentSeven
      text={text}
      buttonIndex={buttonIndex}
      isMobile={isMobile}
      handleDivClick={handleDivClick}
      handleTextClick={handleTextClick}
      getStyle={getStyle}
      getElementStyle={getElementStyle}
      index={index}
      isEdited={isEdited}
      uniqueId={uniqueId}
      elementContent={elementContent}
      handleImageClick={handleImageClick}
      handleDivButtonClick={handleDivButtonClick}
      handleCardClick={handleCardClick}
    />,
    <HeroComponentEight
      text={text}
      buttonIndex={buttonIndex}
      isMobile={isMobile}
      handleDivClick={handleDivClick}
      handleTextClick={handleTextClick}
      getStyle={getStyle}
      getElementStyle={getElementStyle}
      index={index}
      isEdited={isEdited}
      uniqueId={uniqueId}
      elementContent={elementContent}
      handleImageClick={handleImageClick}
      handleDivButtonClick={handleDivButtonClick}
      handleCardClick={handleCardClick}
    />,
  ];
};
