import React, { useContext } from "react";
import { DashContext } from "../DashboardChecker/DashboardContext";
import { useLocation } from "react-router-dom";

const ElementArray = () => {
  const {
    heroIndex,
    navIndex,
    featuresWithCardIndex,
    featuresIndex,
    testimonialIndex,
    faqIndex,
    teamIndex,
    contactIndex,
    footerIndex,
    navComponents,
    heroComponents,
    featuresWithCardsComponent,
    featuresComponents,
    testimonialComponent,
    faqComponent,
    teamComponent,
    contactComponent,
    footerComponent,
    text,
    buttonIndex,
    isMobile,
    isFocused,
    setIsFocused,
    backgroundStyle,
    clickedIndex,
    setClickedIndex,
    handleFocus,
    handleBlur,
    currentSection,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    divStyles,
    defaultBackgroundColor,
    elementStyles,
  } = useContext(DashContext);
  const location = useLocation();

  const getStyle = (id) => {
    if (divStyles[id] && Object.keys(divStyles[id]).length > 0) {
      return divStyles[id];
    }
    return { background: defaultBackgroundColor };
  };

  const getElementStyle = (id) => {
    return elementStyles[id] || {};
  };

  const navElement = navComponents({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
  })[navIndex];
  const heroElement = heroComponents({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    getStyle,
    getElementStyle,
  })[heroIndex];
  const featuresWithCardElement = featuresWithCardsComponent({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    getStyle,
    getElementStyle,
  })[featuresWithCardIndex];
  const featuresElement = featuresComponents({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    getStyle,
    getElementStyle,
  })[featuresIndex];
  const testimonialElement = testimonialComponent({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    getStyle,
    getElementStyle,
  })[testimonialIndex];
  const faqElement = faqComponent({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    getStyle,
    getElementStyle,
  })[faqIndex];
  const teamElement = teamComponent({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    getStyle,
    getElementStyle,
  })[teamIndex];
  const contactElement = contactComponent({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    getStyle,
    getElementStyle,
  })[contactIndex];
  const footerElement = footerComponent({
    text,
    buttonIndex,
    isMobile,
    backgroundStyle,
    isFocused,
    setIsFocused,
    handleFocus,
    handleBlur,
    location,
    handleDivClick,
    handleTextClick,
    handleTextareaChange,
    handleColorClick,
    handleFontSizeClick,
    handleFontWeightClick,
    handleFontStyleClick,
    handleFontFamilyClick,
    handleTextAlignmentClick,
    getStyle,
    getElementStyle,
  })[footerIndex];

  const elements = [
    {
      index: navIndex,
      element: navElement,
    },
    {
      index: heroIndex,
      element: heroElement,
    },
    {
      index: featuresWithCardIndex,
      element: featuresWithCardElement,
    },
    {
      index: featuresIndex,
      element: featuresElement,
    },
    {
      index: testimonialIndex,
      element: testimonialElement,
    },
    { index: faqIndex, element: faqElement },
    { index: teamIndex, element: teamElement },
    { index: footerIndex, element: footerElement },
  ];

  return {
    elements,
    navElement,
    heroElement,
    featuresWithCardElement,
    featuresElement,
    testimonialElement,
    faqElement,
    teamElement,
    contactElement,
    footerElement,
    heroIndex,
    navIndex,
    featuresWithCardIndex,
    featuresIndex,
    testimonialIndex,
    faqIndex,
    teamIndex,
    contactIndex,
    footerIndex,
    clickedIndex,
    setClickedIndex,
  };
};

export default ElementArray;
